name: Publish and deploy project-web

on:
  push:
    branches: [ main ]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '18.x'

      - name: Cache
        uses: actions/cache@v4.0.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build application
        run: |
          npm install --no-audit
          npx ng build --configuration production --output-path=dist

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/kebryansg/web-inspect-bbf:latest .
          docker push ghcr.io/kebryansg/web-inspect-bbf:latest

  deploy-vps:
    runs-on: ubuntu-latest
    needs: create-docker-image
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into Server
        run: |
          sshpass -p "${{ secrets.AUTH_PASS }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
            cd /root/web-inspect-bbf
            docker login ghcr.io -u kebryansg -p ${{ secrets.TOKEN_CD }}
            docker pull ghcr.io/kebryansg/web-inspect-bbf:latest
            docker stop web_inspect_bbf && docker rm web_inspect_bbf
            docker run -d \
              --name web_inspect_bbf \
              -p 3000:3000 \
              --restart always \
              --env-file .env \
              ghcr.io/kebryansg/web-inspect-bbf:latest
          EOF

