name: Build, publish and deploy project to Simply

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '18.x'

      - name: Cache
        uses: actions/cache@v4.0.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build application
        run: | 
          npm install --no-audit
          npx ng build --configuration production --output-path=dist

      - name: Deploy to SmarterASP.NET
        uses: jahbenjah/SmarterASP.NET-web-deploy@1.0.0.alpha.8
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: '\dist\'
          target-delete: true
